### ISSUE TITLE
Question about APP_ID and APP_SECRET

### ISSUE THREAD

**Issue by urielkdev** [AceExpert/ewelink-api-python#1]
hi @AceExpert , I have a question, i'm starting a project in another language for ewelink-api too. I would like to know how you got APP_ID and APP_SECRET. Is it paid?

**Comment by AceExpert** [comment]
Hello @urielkdev,
I myself do not know how was APP_ID and APP_SECRET got. This project being a port of the original one in node/javascript has these secrets in the constants. I have copied them , but I am still not sure how they have got, maybe the original project https://github.com/skydiver/ewelink-api was made by the employees at ewelink or something?

**Comment by sputh-the-pigeon** [comment]
Take a look here https://coolkit-technologies.github.io/eWeLink-API/#/en

**Comment by AceExpert** [comment]
The v2 of the api isn't working, so for now the appid and app_secret of this library are working correctly with v1 api. Seems like v2 api needs you to apply for an app_id
